'use strict';

module.exports = app => {
  const { router, controller } = app;
  const adminauth = app.middleware.adminauth();
  router.post('/api/admin/checkRegister', controller.admin.login.checkRegister);
  router.post('/api/admin/checkLogin', controller.admin.login.checkLogin);
  router.post('/api/admin/upload', controller.blog.upload.index);
  router.get('/api/admin/getTypeInfo', adminauth, controller.admin.addArticle.getTypeInfo);
  router.post('/api/admin/addArticleType', adminauth, controller.admin.addArticle.addArticleType);
  router.post('/api/admin/addArticle', adminauth, controller.admin.addArticle.addArticle);
  router.post('/api/admin/updateArticle', adminauth, controller.admin.addArticle.updateArticle);
  router.post('/api/admin/getArticleList', adminauth, controller.admin.articleList.getArticleList);
  router.post('/api/admin/changePublishStatus', adminauth, controller.admin.articleList.changePublishStatus);
  router.get('/api/admin/delArticleById/:id', adminauth, controller.admin.articleList.delArticleById);
  router.get('/api/admin/getArticleById/:id', adminauth, controller.admin.articleList.getArticleById);
  router.post('/api/admin/userSetting/updateUserInfo', adminauth, controller.admin.userSetting.updateUserInfo);
  router.get('/api/admin/userSetting/getUserInfoById/:id', adminauth, controller.admin.userSetting.getUserInfoById);
  router.post('/api/admin/advertiseManage/addAdvertise', adminauth, controller.admin.advertiseManage.addAdvertise);
  router.post('/api/admin/advertiseManage/getAdvertiseList', adminauth, controller.admin.advertiseManage.getAdvertiseList);
  router.post('/api/admin/advertiseManage/updateAdvertise', adminauth, controller.admin.advertiseManage.updateAdvertise);
  router.post('/api/admin/advertiseManage/updateAdvertiseIsShow', adminauth, controller.admin.advertiseManage.updateAdvertiseIsShow);
  router.get('/api/admin/advertiseManage/deleteAdvertiseById/:id', adminauth, controller.admin.advertiseManage.deleteAdvertiseById);
  router.get('/api/admin/about/getAbout', adminauth, controller.admin.about.getAbout);
  router.post('/api/admin/about/updateAbout', adminauth, controller.admin.about.updateAbout);
  router.post('/api/admin/talk/getTalkList', adminauth, controller.admin.talk.getTalkList);
  router.get('/api/admin/talk/getTalkById/:id', adminauth, controller.admin.talk.getTalkById);
  router.post('/api/admin/talk/updateTalk', adminauth, controller.admin.talk.updateTalk);
  router.get('/api/admin/talk/deleteTalkById/:id', adminauth, controller.admin.talk.deleteTalkById);
  router.post('/api/admin/novel/addNovel', adminauth, controller.admin.novel.addNovel);
  router.post('/api/admin/novel/updateNovel', adminauth, controller.admin.novel.updateNovel);
  router.get('/api/admin/novel/getNovelById/:id', adminauth, controller.admin.novel.getNovelById);
  router.post('/api/admin/novel/getNovelList', adminauth, controller.admin.novel.getNovelList);
  router.get('/api/admin/novel/deleteNovelById/:id', adminauth, controller.admin.novel.deleteNovelById);
  router.post('/api/admin/novel/getChapterList', adminauth, controller.admin.novel.getChapterList);
  router.get('/api/admin/novel/getChapterById/:id', adminauth, controller.admin.novel.getChapterById);
  router.post('/api/admin/novel/addChapter', adminauth, controller.admin.novel.addChapter);
  router.get('/api/admin/novel/deleteChapterById/:id', adminauth, controller.admin.novel.deleteChapterById);
};
